DROP TABLE post IF EXISTS;

create table post (
    post_id bigint generated by default as identity,
    title varchar(255) not null,
    writer varchar(255) not null,
    password varchar(255) not null,
    content longtext not null,
    created timestamp,
    modified timestamp,
    viewed integer,
    likes integer,
    isNew bit,
    primary key (post_id)
);

DROP TABLE comment IF EXISTS;

create table comment (
    comment_id bigint generated by default as identity,
    writer varchar(255) not null,
    password varchar(255) not null,
    content longtext not null,
    created timestamp,
    modified timestamp,
    likes integer,
    primary key (comment_id),
    FOREIGN key (post_id) REFERENCES post (post_id)
);

DROP TABLE hashtag EXISTS;

create table hashtag (
    hashtag_id bigint generated by default as identity,
    name varchar(50) not null,
    primary key (hashtag_id)
);

DROP TABLE hashtag_post EXISTS;

create table hashtag_post (
    hashtag_post_id bigint generated by default as identity,
    FOREIGN key (post_id) REFERENCES post (post_id),
    FOREIGN key (hashtag_id) REFERENCES hashtag (hashtag_id)
);